### ISSUE TITLE
Alarm app need two permission for stable alarm system

### ISSUE THREAD

**Issue by jja08111** [geisterfurz007/random-alarm#18]
Hi, I released an alarm app at the play store using your open-source, thank you so much.

While building the app, I found out that two permissions are required for a stable alarm system.

1. Display over other apps
2. Ignore battery optimization

Those permissions are should be required in the upper Android 10 version. If the first permission is not allowed, the app cannot be displayed on the screen when the app is not running or is running in the background. If the second permission is not allowed, the alarm sometimes does not work. 

Therefore, this repo should have a description or code added to the above permission.

**Comment by mvarendorff** [comment]
Hey, that's awesome! Given that this was mostly a fun project for myself, I am happy to see that someone took the time to get it store ready, thanks for that! Do you have a link to the playstore listing, I would love to see it in action when it's not running as debug build on my phone!

As for the permissions, I definitely agree! It's been a while since I had this project open on my computer and there are a few other projects I am working on currently so I don't think I will find the time to do so. I would be happy to accept pull requests or archive this repository and link to a fork of it should you create and plan to maintain one!

**Comment by jja08111** [comment]
Cool! I will try to make a PR, but I don't know when it will be because I don't have much time.

My app is posted [here](https://play.google.com/store/apps/details?id=io.github.jja08111.good_night_app). I wouldn't have been able to release my app without your app. Thank you very much!
