### ISSUE TITLE
'alarm_status.g.dart' and 'observable_alarm.g.dart' are not in the list 

### ISSUE THREAD

**Issue by Michellezxc** [geisterfurz007/random-alarm#20]
'alarm_status.g.dart' and 'observable_alarm.g.dart' are not in the list. Can you include them inside? Much appreciated!!

**Comment by mvarendorff** [comment]
What do you mean with "not in the list"? Did you run the build runner with `flutter packages pub run build_runner run`? See https://github.com/geisterfurz007/random-alarm/issues/13#issuecomment-701628978 for a little more info.

**Comment by Michellezxc** [comment]
According to this URL, https://github.com/google/json_serializable.dart/tree/master/example/lib . 'g.dart' is included in the list. So, I am wondering whether there is any 'g.dart' that supports the 'dart' files? For example. there is a 'example.g.dart' supporting 'example.dart'.

Also, I did run the 'flutter packages pub run build_runner run' already but it doesn't succeed.

**Comment by mvarendorff** [comment]
I don't include generated files in version control because every user can generate them themselves and having them in version control only causes other errors that need an additional commandline switch to deal with. That's why there are no `.g.dart` files in my repository.

If the build_runner command failed, it would be good to have the output or at least error of it to fix that because it's the only sensible way of getting to the generated files.
